export default {
  SET_ITEM: "SET_ITEM",
  APPEND_ITEM_TO_LIST: "APPEND_ITEM_TO_LIST",
  REMOVE_ITEM_FROM_LIST: "REMOVE_ITEM_FROM_LIST",
  SET_SENDER_INFO: "SET_SENDER_INFO",
  SET_CLIENT_INFO: "SET_CLIENT_INFO",
  SET_CORE_INFO: "SET_CORE_INFO",
};
